= Cloud CI Conditional Plugin for Gradle

Simple plugin that allows for configuration to only become available when
  running under specific cloud CI providers.This just leads to a more beautiful
  DSL than having to use `if` conditions and simultaneously having to remember
  which environmental variables to check.

Simply becasue typing stuff like this looks ugly in a Gradle build script

[source,groovy]
----
if( System.getenv()['APPVEYOR'] ) {
  test {
    jvmArgs '-Xmx:2048m'
  }
}
----

Now you can have a slicker DSL to do the same for a variety of CI products.

== Applying the plugin

See https://plugins.gradle.org/plugin/org.ysb33r.cloudci for up to date information
on applying this plugin.

== Configuration

.Appveyor
[source,groovy]
----
cloudci {
    appveyor { // <1>
       test {
         jvmArgs '-Xmx:2048m' // <2>
       }
    }
}
----
<1> Only run this configuration when on https://ci.appveyor.com[AppVeyor]
<2> By example you can set the JVM Args for tests when on Appveyor

.Travis CI
[source,groovy]
----
cloudci {
    travisci { // <1>
       test {
         jvmArgs '-Xmx:2048m'
       }
    }
}
----
<1> Only run this configuration when on https://travis-ci.org[Travis CI]

.Circle CI
[source,groovy]
----
cloudci {
    circleci { // <1>
       test {
         jvmArgs '-Xmx:2048m'
       }
    }
}
----
<1> Only run this configuration when on https://circleci.com[Circle CI]

.Jenkins CI
[source,groovy]
----
cloudci {
    jenkinsci { // <1>
       test {
         jvmArgs '-Xmx:2048m'
       }
    }
}
----
<1> Only run this configuration when on a https://jenkins.io/index.html[Jenkins CI] server.

.Any supported CI
[source,groovy]
----
cloudci {
    any { // <1>
       test {
         jvmArgs '-Xmx:2048m'
       }
    }
}
----
<1> Run this configuration if executed under any of the supported CI environments.