= Cloud CI Conditional Plugin for Gradle
:toc:

Simple plugin that allows for configuration to only become available when
  running under specific cloud CI providers.This just leads to a more beautiful
  DSL than having to use `if` conditions and simultaneously having to remember
  which environmental variables to check.

Simply because typing stuff like this looks ugly in a Gradle build script

[source,groovy]
----
if( System.getenv()['APPVEYOR'] ) {
  test {
    jvmArgs '-Xmx:2048m'
  }
}
----

Now you can have a slicker DSL to do the same for a variety of CI products.

== Applying the plugin

See https://plugins.gradle.org/plugin/org.ysb33r.cloudci for up to date information
on applying this plugin.

== Conditional Configuration

=== Appveyor

[source,groovy]
----
cloudci {
    appveyor { // <1>
       test {
         jvmArgs '-Xmx:2048m' // <2>
       }
    }
}
----
<1> Only run this configuration when on https://ci.appveyor.com[AppVeyor]
<2> By example you can set the JVM Args for tests when on Appveyor

=== Bamboo

[source,groovy]
----
ci {
    bamboo { // <1>
       test {
         jvmArgs '-Xmx:2048m'
       }
    }
}
----
<1> Only use this configuration if an https://www.atlassian.com/software/bamboo[Atlassian Bamboo] agent is detected.

=== Circle CI

[source,groovy]
----
ci {
    circleci { // <1>
       test {
         jvmArgs '-Xmx:2048m'
       }
    }
}
----
<1> Only run this configuration when on https://circleci.com[Circle CI].

=== Codeship

[source,groovy]
----
ci {
    codeship { // <1>
       test {
         jvmArgs '-Xmx:2048m'
       }
    }
}
----
<1> Only run this configuration when on https://codeship.com/[Codeship].

=== Drone

[source,groovy]
----
ci {
    drone { // <1>
       test {
         jvmArgs '-Xmx:2048m'
       }
    }
}
----
<1> Only use this configuration if a https://drone.io[Drone agent] is detected.

=== GitLab Runners

[source,groovy]
----
ci {
    gitlabci { // <1>
       test {
         jvmArgs '-Xmx:2048m'
       }
    }
}
----
<1> Only use this configuration if a https://gitlab.com[GitLab runner] is detected.

=== Go CD

[source,groovy]
----
ci {
    gocd { // <1>
       test {
         jvmArgs '-Xmx:2048m'
       }
    }
}
----
<1> Only run this configuration when on https://www.gocd.org/[Go CD].

=== Jenkins CI

[source,groovy]
----
ci {
    jenkinsci { // <1>
       test {
         jvmArgs '-Xmx:2048m'
       }
    }
}
----
<1> Only run this configuration when on a https://jenkins.io/index.html[Jenkins CI] server.

=== Teamcity

[source,groovy]
----
ci {
    travisci { // <1>
       test {
         jvmArgs '-Xmx:2048m'
       }
    }
}
----
<1> Only run this configuration when on https://www.jetbrains.com/teamcity[Jetbrains Teamcity]

=== Travis CI

[source,groovy]
----
ci {
    travisci { // <1>
       test {
         jvmArgs '-Xmx:2048m'
       }
    }
}
----
<1> Only run this configuration when on https://travis-ci.org[Travis CI]

.Any supported CI
[source,groovy]
----
ci {
    any_ci { // <1>
       test {
         jvmArgs '-Xmx:2048m'
       }
    }
}
----
<1> Run this configuration if executed under any of the supported CI environments. Use `any_ci`, as the use of `any` from previous releases is deprecated).

.No CI
[source,groovy]
----
ci {
    no_ci { // <1>
       test {
         jvmArgs '-Xmx:2048m'
       }
    }
}
----
<1> Only run this configuration if none of the supported CI environments are detected.

== Pushing test results to Appveyor's Build Worker API

If you have any tasks based up on the Gradle `Test` class, you can have the test results pushed in real time via the Build Worker API. All you need to do is

[source,groovy]
----
plugins {
  id 'org.ysb33r.cloudci.appveyor.testreporter' version '<VERSION>' // <1>
}
----
<1> See https://plugins.gradle.org/plugin/org.ysb33r.cloudci.appveyor.testreporter for up to date information
    on applying this plugin.

Now when you run your tests the results will be posted when your build runs on Appveyor.

Currently only the `Test` task type is supported, which will cover most cases for JVM projects.
